language: php
php:
  - 7.1

before_install:
  - nvm install 10
install: npm install

script:
  - bash ./deploy/deploy.sh

cache:
  directories:
    - node_modules
    - cache

dist: trusty
sudo: false
