version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers

    working_directory: ~/docs

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: sudo apt-get install bc
      - run: npm i

      - save_cache:
          paths:
            - node_modules
            - cache
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: .circleci/deploy.sh
