version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers

    working_directory: ~/docs

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm i

      - save_cache:
          paths:
            - node_modules
            - cache
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: .circleci/deploy.sh
