name: Build API Docs

on:
  schedule:
    - cron: "0 * * * *"

  push:
    paths-ignore:
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        language: ['js', 'php']

    name: '${{ matrix.language }}'

    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Build
        run: scripts/build-${{ matrix.language }}.sh

      - name: Commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "${{ matrix.language}}: update (flarum/core@FLARUM_SHA)" docs/${{ matrix.language }}

      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}